nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.2.1.cjs

enableColors: true
enableHyperlinks: true
enableImmutableInstalls: true
enableProgressBars: true
enableTelemetry: false

pnpEnableEsmLoader: true
pnpMode: strict

npmPublishRegistry: https://npm.pkg.github.com
npmPublishAccess: restricted